version: "3.8"

services:

  nginx:
    image: nginx:latest
    volumes:
      - ./out:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./out/_next/static/image:/media
    restart: always
    ports:
      - "80:80"
      - "443:443"